name: "Deploy Restoran Template"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and Deploy Template"

    steps:
      # Step 1: Checkout Repository
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (optional, if needed for build tools)
      - name: "Setup Node.js Environment"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Dependencies (if applicable)
      - name: "Install Dependencies"
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No dependencies to install."
          fi

      # Step 4: Build Project (if applicable)
      - name: "Build the Template"
        run: |
          if [ -f package.json ]; then
            npm run build
          else
            echo "No build step defined."
          fi

      # Step 5: Deploy to GitHub Pages
      - name: "Deploy to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Specify the directory to publish (change if necessary)

  validate:
    runs-on: ubuntu-latest
    name: "Validate Template Files"

    steps:
      # Step 1: Checkout Repository
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      # Step 2: Validate Files
      - name: "Check Required Files"
        run: |
          required_files=("LICENSE.txt" "index.html" "assets/" "css/" "js/" "images/")
          for file in "${required_files[@]}"; do
            if [ ! -e "$file" ]; then
              echo "Error: $file is missing."
              exit 1
            fi
          done
          echo "All required files are present."

      # Step 3: Lint HTML (optional)
      - name: "Lint HTML Files"
        run: |
          npm install -g htmlhint
          htmlhint "**/*.html"

